version: '3.7'

services:
  web:
    build:
      context: ./xb1
      dockerfile: Dockerfile.ci-test
    volumes:
      - ./xb1/:/usr/src/xb1/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    ofelia.enabled: "true"
      ofelia.job-exec.db_backup.schedule: "@weekly"
      ofelia.job-exec.db_backup.command: 'sh -c "python3 manage.py dumpdata --all --natural-foreign --natural-primary -e contenttypes -e auth.Permission --indent 2 > dumps/$$(date +%F-%R).json"'
      ofelia.job-exec.article_update.schedule: "@daily"
      ofelia.job-exec.article_update.command: "python3 manage.py update_articles"
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=xb1_user
      - POSTGRES_PASSWORD=hello_xb1
      - POSTGRES_DB=xb1_dev
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - web
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  postgres_data:
