# Generated by Django 3.0.3 on 2020-04-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=20, verbose_name='Name')),
                ('itemPrice', models.CharField(max_length=10, verbose_name='Price')),
                ('itemDesc', models.CharField(max_length=200, verbose_name='Description')),
                ('itemType', models.PositiveSmallIntegerField(choices=[(0, 'Top'), (1, 'Sale'), (2, 'None'), (3, 'New')], default=2, verbose_name='Item type')),
                ('itemActive', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
