# Generated by Django 3.0.3 on 2020-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20200415_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderFirstName', models.CharField(max_length=30, verbose_name='FirstName')),
                ('orderLastName', models.CharField(max_length=30, verbose_name='LastName')),
                ('orderEmail', models.EmailField(max_length=64, verbose_name='Email')),
                ('orderAddressCity', models.CharField(max_length=20, verbose_name='City')),
                ('orderAddressStreet', models.CharField(max_length=20, verbose_name='Street')),
                ('orderAddressStreetNumber', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='StreetNumber')),
                ('orderAddressPostNumber', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='PostNumber')),
                ('orderItems', models.ManyToManyField(blank=True, to='eshop.ShopItem', verbose_name='OrderItems')),
            ],
        ),
    ]
