# Generated by Django 3.0.3 on 2020-04-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_shoporder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoporder',
            name='orderItems',
        ),
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopItemCount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='ItemCount')),
                ('shopItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eshop.ShopItem', verbose_name='ShopItem')),
                ('shopOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.ShopOrder', verbose_name='ShopOrder')),
            ],
        ),
    ]
