# Generated by Django 3.0.3 on 2020-04-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20200421_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='itemImg',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='ShopItems', verbose_name='Image'),
        ),
    ]
