# Generated by Django 3.0.3 on 2020-04-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_shopitem_itemimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='itemImg',
            field=models.ImageField(default='default.jpg', upload_to='ShopItems', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='ShopPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentPrice', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='TotalPrice')),
                ('paymentReceived', models.BooleanField(default=False, verbose_name='Received')),
                ('paymentVariableSymbol', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='VariableSymbol')),
                ('paymentSpecificSymbol', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='SpecificSymbol')),
                ('paymentOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.ShopOrder', verbose_name='ShopOrder')),
            ],
        ),
    ]
