# Generated by Django 3.0.3 on 2020-10-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_auto_20200531_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='itemDesc',
            field=models.TextField(verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='itemName',
            field=models.CharField(max_length=100, verbose_name='Název produktu'),
        ),
    ]
