# Generated by Django 3.0.3 on 2020-10-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_auto_20201007_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='itemActive',
            field=models.BooleanField(default=True, verbose_name='Activate'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='itemDesc',
            field=models.CharField(max_length=400, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='itemName',
            field=models.CharField(max_length=50, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='itemType',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Top'), (1, 'Sale'), (2, 'None'), (3, 'New')], default=2, verbose_name='Product type'),
        ),
    ]
