# Generated by Django 3.0.3 on 2020-10-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_auto_20201027_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='shoporderitem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='shoppayment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Deleted'),
        ),
    ]
