# Generated by Django 3.0.3 on 2020-11-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0013_shoporder_orderuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopPayment',
        ),
    ]
