# Generated by Django 3.0.3 on 2020-11-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0014_delete_shoppayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopOrderItem',
        ),
    ]
