# Generated by Django 3.0.3 on 2020-11-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201123_2102'),
        ('eshop', '0015_delete_shoporderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopOrder',
        ),
    ]
