# Generated by Django 3.0.3 on 2020-11-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0016_delete_shoporder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopItem',
        ),
    ]
