# Generated by Django 3.0.3 on 2020-04-08 18:51

import datetime
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200318_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='allow_comments',
            field=models.BooleanField(default=False, verbose_name='Comments allowed'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_state',
            field=models.CharField(choices=[('H', 'Hidden'), ('P', 'Published')], default='H', max_length=2, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='article',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='article',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Published from'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published to'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='article',
            name='sources',
            field=models.TextField(blank=True, null=True, verbose_name='Sources'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, to='articles.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.Tag'),
        ),
    ]
