# Generated by Django 3.0.3 on 2020-04-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200408_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_state',
            field=models.CharField(choices=[(0, 'Hidden'), (1, 'Published')], default=0, max_length=2, verbose_name='State'),
        ),
    ]
