# Generated by Django 3.0.3 on 2020-04-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200409_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Hidden'), (1, 'Published')], default=0, verbose_name='State'),
        ),
    ]
