# Generated by Django 3.0.3 on 2020-04-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_comment_forum_forumcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails', verbose_name='Thumbnail'),
        ),
    ]
