# Generated by Django 3.0.3 on 2020-04-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
