# Generated by Django 3.0.3 on 2020-04-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_delete_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, to='articles.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.Tag', verbose_name='Tag'),
        ),
    ]
