# Generated by Django 3.0.3 on 2020-04-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_preview_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Preview text'),
        ),
    ]
