# Generated by Django 3.0.3 on 2020-04-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200422_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='article_content_images/')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
