# Generated by Django 3.0.3 on 2020-04-29 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Posted on'),
        ),
    ]
