# Generated by Django 3.0.3 on 2020-04-30 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_from',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Published from'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Posted on'),
        ),
    ]
