# Generated by Django 3.0.3 on 2020-04-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200421_2125'),
        ('articles', '0015_auto_20200430_1127'),
    ]

    operations = [
    ]
