# Generated by Django 3.0.3 on 2020-05-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_merge_20200504_1345'),
        ('articles', '0017_merge_20200506_0047'),
    ]

    operations = [
    ]
