# Generated by Django 3.0.3 on 2020-06-10 12:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20200521_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
