# Generated by Django 3.0.3 on 2020-06-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20200610_1419'),
        ('articles', '0019_auto_20200515_0043'),
    ]

    operations = [
    ]
