# Generated by Django 3.0.3 on 2020-06-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_merge_20200617_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Popis vlákna'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Popis tématu'),
        ),
    ]
