# Generated by Django 3.0.3 on 2020-10-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20201013_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Comments allowed'),
        ),
    ]
