# Generated by Django 3.0.3 on 2020-10-28 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20201028_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_from',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Published from'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_to',
            field=models.DateField(blank=True, null=True, verbose_name='Published to'),
        ),
    ]
