# Generated by Django 3.0.3 on 2020-10-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20201027_2125'),
        ('articles', '0028_auto_20201028_1702'),
    ]

    operations = [
    ]
