# Generated by Django 3.0.3 on 2020-10-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_article_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='forum',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Deleted'),
        ),
    ]
