# Generated by Django 3.0.3 on 2020-11-15 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201115_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartentry',
            name='specification',
        ),
        migrations.AddField(
            model_name='cartentry',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.SpecificationEntry'),
        ),
    ]
