# Generated by Django 3.0.3 on 2020-11-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201115_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartentry',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cartentry',
            name='specification',
        ),
        migrations.AddField(
            model_name='cartentry',
            name='specification',
            field=models.ManyToManyField(blank=True, to='shop.SpecificationEntry'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('creation', models.DateTimeField(verbose_name='Creation date')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cartentry',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Cart', verbose_name='Cart'),
        ),
    ]
