# Generated by Django 3.0.3 on 2020-11-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201116_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='order',
        ),
    ]
