# Generated by Django 3.0.3 on 2020-11-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201116_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Active'),
            preserve_default=False,
        ),
    ]
