version: '3.7'

services:
  web:
    build:
        context: ./xb1
        dockerfile: Dockerfile.ci
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./xb1/:/usr/src/xb1/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
        - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=xb1_user
      - POSTGRES_PASSWORD=hello_xb1
      - POSTGRES_DB=xb1_dev

volumes:
  postgres_data:
