# Generated by Django 3.0.3 on 2020-03-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200318_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
