# Generated by Django 3.0.3 on 2020-04-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200412_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postalCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code'),
        ),
    ]
