# Generated by Django 3.0.3 on 2020-04-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200421_1654'),
        ('core', '0006_auto_20200419_1950'),
    ]

    operations = [
    ]
