# Generated by Django 3.0.3 on 2020-05-05 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20200504_1858'),
        ('core', '0009_merge_20200430_1720'),
    ]

    operations = [
    ]
