# Generated by Django 3.0.3 on 2020-05-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200512_1445'),
        ('core', '0010_merge_20200506_0047'),
    ]

    operations = [
    ]
