# Generated by Django 3.0.3 on 2020-05-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20200513_2227'),
        ('core', '0010_auto_20200504_1345'),
    ]

    operations = [
    ]
