# Generated by Django 3.0.3 on 2020-06-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200515_0043'),
        ('core', '0013_auto_20200521_1554'),
    ]

    operations = [
    ]
