# Generated by Django 3.0.3 on 2020-10-28 20:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_merge_20201028_1831'),
        ('eshop', '0011_auto_20201027_2015'),
        ('core', '0016_auto_20201028_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 10, 28, 21, 14, 44, 208510), verbose_name='Timestamp')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Action')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='Article')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Comment', verbose_name='Comment')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Forum', verbose_name='Comment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.ShopOrder', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
