# Generated by Django 3.0.3 on 2020-10-29 21:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_merge_20201028_1831'),
        ('core', '0018_auto_20201028_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Forum', verbose_name='Forum'),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 22, 15, 36, 388099), verbose_name='Timestamp'),
        ),
    ]
