# Generated by Django 3.0.3 on 2020-10-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201029_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Timestamp'),
        ),
    ]
