# Generated by Django 3.0.3 on 2020-11-23 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_payment'),
        ('core', '0020_auto_20201029_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='Order'),
        ),
    ]
