# Generated by Django 3.0.3 on 2020-12-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_log_order_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingletonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('singletonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.SingletonModel')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
            ],
            bases=('core.singletonmodel',),
        ),
    ]
