# Generated by Django 3.0.3 on 2020-12-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_message_singletonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Timestamp'),
        ),
    ]
