# Generated by Django 3.0.3 on 2021-01-05 23:33

from django.db import migrations, models
import xb1.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201208_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=xb1.core.models.GenerateFilepath('profile_image'), verbose_name='Image'),
        ),
    ]
